version: '2.4'
services:
  db:
    image: postgres:alpine
    container_name: maqe-db
    ports:
      - "5432"
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s
  api:
    image: node:12.6.0-slim
    command: ["yarn", "dev"]
    container_name: maqe-api
    depends_on:
      db:
        condition: service_healthy
    entrypoint: /usr/src/app/docker-entrypoint.sh
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./server:/usr/src/app:delegated
    working_dir: /usr/src/app
